// Generated by CoffeeScript 1.10.0
var assert;

assert = chai.assert;

describe('deck', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    deck = new Deck();
    return hand = deck.dealPlayer();
  });
  describe('hit', function() {
    return it('should give the last card from the deck', function() {
      assert.strictEqual(deck.length, 50);
      assert.strictEqual(deck.last(), hand.hit().at(hand.length - 1));
      return assert.strictEqual(deck.length, 49);
    });
  });
  return describe('scoring', function() {
    return it('should add up the hand\'s score correctly', function() {
      return assert.strictEqual(hand.at(0).get('value') + hand.at(1).get('value'), hand.minScore());
    });
  });
});
